resources:
- ../../base

commonLabels:
  app: dev


namespace: dev

patchesStrategicMerge: 
  - wordpress_svc.yaml


commonAnnotations:
  app: kustom-dev

namePrefix:
  dev-

nameSuffix:
  -v1




# configMapGenerator:
# - name: mykustom-map
#   env: config.properties