resources: 
- ../../base/docker_secret.yaml 
- ../../base/wordpress-deployment.yaml 
- ../../base/wordpress-service.yaml 
- ../../base/wordpress-pvc.yaml 
- ../../base/mysql-deployment.yaml 
- ../../base/mysql-service.yaml 
- ../../base/mysql-pvc.yaml 
- ../../base/secret.yaml 

commonLabels:
  app: dev


namespace: dev 

commonAnnotations:
  app: kustom-dev

namePrefix:
  dev-

nameSuffix:
  -v1

# configMapGenerator:
# - name: mykustom-map
#   env: config.properties