apiVersion: v1
kind: Pod
metadata:
  name: mysql-data-inspection
  namespace: prod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    volumeMounts:
    - name: mysql-storage
      mountPath: /mnt
  volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-pv-claim
